site_name: Computational methods for historical texts
repo_url: https://github.com/natesheehan/cookbook
theme:
  features:
    - content.action.edit
  name: mkdocs
  nav_style: dark
  highlightjs: true
  hljs_languages:
    - yaml
    - python